# Generated by Django 3.0.6 on 2020-07-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_like_num'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='like_blog',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='main.Blog'),
        ),
    ]
